server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1435;databaseName=HouseRentalDB;encrypt=true;trustServerCertificate=true}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:Dat12345!}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServerDialect
      hibernate.format_sql: true
      hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  thymeleaf:
    cache: false

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:datphhe180379@fpt.edu.vn}
    password: ${SPRING_MAIL_PASSWORD:mqdh xlvr acoy xitn}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: 6379
sepay:
  secret-key: QD3Uo8YkDJxT0zy/ctP7OX8ZDcbskxeuk66JT8WurtoIV7T/YbdAtvPGh1bflbDd

logging:
  level:
    org:
      hibernate:
        SQL: OFF
        type:
          descriptor:
            sql:
              BasicBinder: OFF