server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: strict

spring:
  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

  aws:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ap-southeast-2
    s3:
      bucket: house-rental

app:
  security:
    remember-me:
      key: tuilarememberkey
      validity: 604800
  email:
    verification:
      expiration: 86400
    password-reset:
      expiration: 3600
